<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <TargetFrameworks>net40;netcoreapp3.0</TargetFrameworks>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <UseWPF>true</UseWPF>
    <PackageId>ALampy.XamlFontPicker.WPF</PackageId>
    <Authors>ALampy</Authors>
    <Company>ALampy</Company>
    <Product>ALampy.XamlFontPicker.WPF</Product>
    <RepositoryUrl>https://github.com/ArcticLampyrid/XamlFontPicker</RepositoryUrl>
    <RootNamespace>ALampy.XamlFontPicker.WPF</RootNamespace>
    <AssemblyName>ALampy.XamlFontPicker.WPF</AssemblyName>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageTags>WPF;Font;FontDialog;FontPicker</PackageTags>
    <PackageDescription>A library providing common FontPicker(Control) and FontDialog for WPF application.</PackageDescription>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework)'=='net40'">
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>

  <ItemGroup>
    <None Include="../README.md" Pack="true" PackagePath="" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
